---
roles:
  - name: chriswayg.msmtp-mailer
  - name: geerlingguy.docker
  - name: geerlingguy.pip

collections:
  - name: community.docker
  - name: community.general
  - name: community.crypto
  - name: ansible.posix
