---
- name: Check if locale {{ locale }} exists
  ansible.builtin.shell:
    cmd: "locale -a | grep -i {{ locale | regex_replace('-', '') | quote }}"
  register: found_locale
  changed_when: no
  failed_when: no

- name: Create locale {{ locale }}
  ansible.builtin.command:
    cmd: >-
      localedef -i {{ locale | regex_replace('(.*)\\..*', '\\1') | quote }}
      -f {{ system_settings_locale | regex_replace('.*\\.(.*)', '\\1') | quote }}
      {{ system_settings_locale | quote }}
  when: found_locale.rc != 0
  changed_when: found_locale.rc != 0

- name: "Set timezone to {{ timezone }}"
  community.general.timezone:
    name: "{{ timezone }}"
  notify: Restart crond

- name: Update and upgrade apt packages
  ansible.builtin.apt:
    upgrade: yes
    autoremove: yes
    update_cache: yes

- name: Install unattended upgrades package
  ansible.builtin.package:
    name: unattended-upgrades
    state: present

- name: Copy unattended-upgrades configuration files in place
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "/etc/apt/apt.conf.d/{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - 10periodic
    - 50unattended-upgrades
