---
- name: Load OS-specific vars
  ansible.builtin.include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
        - main.yml
      paths:
        - 'vars'

- name: Configure the system
  ansible.builtin.include_tasks: essential.yml

- name: Update the packages and configure auto-updates (RedHat-based)
  ansible.builtin.include_tasks: setup-RedHat.yml
  when:
    - ansible_os_family == 'RedHat'

- name: Update the packages and configure auto-updates (Debian-based)
  ansible.builtin.include_tasks: setup-Debian.yml
  when:
    - ansible_os_family == 'Debian'

- name: Configure the user account
  ansible.builtin.include_tasks: user.yml
